### ISSUE TITLE
ko.mapping.toJSON ignores options parameter

### ISSUE THREAD

**Issue by philmueller** [SteveSanderson/knockout.mapping#7]
I guess

<pre>
ko.mapping.toJSON = function (rootObject, options) {
  var plainJavaScriptObject = ko.mapping.toJS(rootObject);
  return ko.utils.stringifyJson(plainJavaScriptObject, <strong><em>options</em></strong>);
};
</pre>

should be

<pre>
ko.mapping.toJSON = function (rootObject, options) {
  var plainJavaScriptObject = ko.mapping.toJS(rootObject, <strong><em>options</em></strong>);
  return ko.utils.stringifyJson(plainJavaScriptObject);
};
</pre>

**Comment by sagacity** [comment]
Fixed problem with ko.mapping.fromJSON ignoring options. Closed by 10d0274a328b729edda427e5777e6374698fa9e5.

**Comment by alexreg** [comment]
This still doesn't work with toJS or toJSON. Basically my 'mapping' parameter (which I presume is options, since it's undocumented) gets ignored.

**Comment by sagacity** [comment]
Can you add a reproduction scenario on jsfiddle?

**Comment by alexreg** [comment]
Just so I'm not wasting time here: how _should_ the mapping object (as given on the ko.mapping documentation page on the KO site) be passed to ko.toJS/ko.toJSON? I only see an options parameter for these functions, so I'm a bit confused.

**Comment by sagacity** [comment]
It should simply be passed in as the only parameter, the options are automatically taken from the mapped object (inside your mapped object there is a **ko_mapping** property), e.g.:

var unmapped = ko.mapping.toJS(mappedViewModel);

**Comment by alexreg** [comment]
Ah right... so I need to set the ko_mapping property to the 'mapping' object mentioned on the KO site. The KO site doesn't mention this at all! This just sounds like documentation needs to be updated. It's not very good atm to be fair. But thanks for the quick reply anyway.

**Comment by sagacity** [comment]
No, this property is set automatically when you create a mapped object. The normal flow is something like:

var mappedViewModel = ko.mapping.fromJS(data);
// do stuff
var unmapped = ko.mapping.toJS(mappedViewModel);

mappedViewModel already contains the ko_mapping property, you don't need to do this manually. This is why it is not documented.

**Comment by alexreg** [comment]
Oh, I see. And I think you mean that the mapping object can only be passed in on fromJS, per the Knockout documentation. e.g.

ko.mapping.fromJS(data, mapping)

but not the corresponding for the toJS/toJSON functions?

**Comment by sagacity** [comment]
Yes, fromJS is intended to be used only with objects created with toJS. I hope this clarifies the problems you are seeing.

**Comment by alexreg** [comment]
Thanks, all is clear now.
